# Generated by Django 3.0.2 on 2020-01-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_auto_20200111_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categorias'},
        ),
    ]
